//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionWebHotel.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alquiler
    {
        public int idAlquiler { get; set; }
        public int alqHabitacion { get; set; }
        public int alqCliente { get; set; }
        public System.DateTime alqFechaIngreso { get; set; }
        public System.DateTime alqFechaSalida { get; set; }
        public string alqObservacion { get; set; }
        public string alqEstado { get; set; }
        public int alqCostoTotal { get; set; }
        public int alqUsuario { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Habitaciones Habitaciones { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
