//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionWebHotel.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contactenos
    {
        public int idContactenos { get; set; }
        public string conNombre { get; set; }
        public string conCorreo { get; set; }
        public string conComentario { get; set; }
    }
}
