//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotelv3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class factura
    {
        public int numFactura { get; set; }
        public string nombreEmisor { get; set; }
        public string telEmisor { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<System.TimeSpan> hora { get; set; }
        public int idHuesped { get; set; }
        public int idRegistro { get; set; }
        public int idConsumo { get; set; }
        public int total { get; set; }
    
        public virtual consumo consumo { get; set; }
        public virtual huesped huesped { get; set; }
        public virtual registro registro { get; set; }
    }
}
