//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotelv3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hotel5Entities : DbContext
    {
        public hotel5Entities()
            : base("name=hotel5Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<consumo> consumo { get; set; }
        public virtual DbSet<empleado> empleado { get; set; }
        public virtual DbSet<factura> factura { get; set; }
        public virtual DbSet<habitacion> habitacion { get; set; }
        public virtual DbSet<huesped> huesped { get; set; }
        public virtual DbSet<queja> queja { get; set; }
        public virtual DbSet<registro> registro { get; set; }
        public virtual DbSet<satisfaccion> satisfaccion { get; set; }
        public virtual DbSet<servicio> servicio { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
