//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotelv3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class huesped
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public huesped()
        {
            this.consumo = new HashSet<consumo>();
            this.factura = new HashSet<factura>();
            this.registro = new HashSet<registro>();
        }
    
        public int idHuesped { get; set; }
        public string nombres { get; set; }
        public string apellido_pat { get; set; }
        public string apellido_mat { get; set; }
        public int edad { get; set; }
        public string sexo { get; set; }
        public System.DateTime fecha_nac { get; set; }
        public string lugar_nac { get; set; }
        public string direccion { get; set; }
        public string tel_casa { get; set; }
        public string tel_celular { get; set; }
        public string correo { get; set; }
        public string rfc { get; set; }
        public Nullable<int> numVisita { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<consumo> consumo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<factura> factura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<registro> registro { get; set; }
    }
}
