#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="hotel5")]
	public partial class EntidadesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void Insertusuario(usuario instance);
    partial void Updateusuario(usuario instance);
    partial void Deleteusuario(usuario instance);
    partial void Insertconsumo(consumo instance);
    partial void Updateconsumo(consumo instance);
    partial void Deleteconsumo(consumo instance);
    partial void Insertempleado(empleado instance);
    partial void Updateempleado(empleado instance);
    partial void Deleteempleado(empleado instance);
    partial void Insertfactura(factura instance);
    partial void Updatefactura(factura instance);
    partial void Deletefactura(factura instance);
    partial void Inserthabitacion(habitacion instance);
    partial void Updatehabitacion(habitacion instance);
    partial void Deletehabitacion(habitacion instance);
    partial void Inserthuesped(huesped instance);
    partial void Updatehuesped(huesped instance);
    partial void Deletehuesped(huesped instance);
    partial void Insertqueja(queja instance);
    partial void Updatequeja(queja instance);
    partial void Deletequeja(queja instance);
    partial void Insertregistro(registro instance);
    partial void Updateregistro(registro instance);
    partial void Deleteregistro(registro instance);
    partial void Insertsatisfaccion(satisfaccion instance);
    partial void Updatesatisfaccion(satisfaccion instance);
    partial void Deletesatisfaccion(satisfaccion instance);
    partial void Insertservicio(servicio instance);
    partial void Updateservicio(servicio instance);
    partial void Deleteservicio(servicio instance);
    #endregion
		
		public EntidadesDataContext() : 
				base(global::Modelo.Properties.Settings.Default.hotel5ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public EntidadesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EntidadesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EntidadesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EntidadesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<usuario> usuario
		{
			get
			{
				return this.GetTable<usuario>();
			}
		}
		
		public System.Data.Linq.Table<consumo> consumo
		{
			get
			{
				return this.GetTable<consumo>();
			}
		}
		
		public System.Data.Linq.Table<empleado> empleado
		{
			get
			{
				return this.GetTable<empleado>();
			}
		}
		
		public System.Data.Linq.Table<factura> factura
		{
			get
			{
				return this.GetTable<factura>();
			}
		}
		
		public System.Data.Linq.Table<habitacion> habitacion
		{
			get
			{
				return this.GetTable<habitacion>();
			}
		}
		
		public System.Data.Linq.Table<huesped> huesped
		{
			get
			{
				return this.GetTable<huesped>();
			}
		}
		
		public System.Data.Linq.Table<queja> queja
		{
			get
			{
				return this.GetTable<queja>();
			}
		}
		
		public System.Data.Linq.Table<registro> registro
		{
			get
			{
				return this.GetTable<registro>();
			}
		}
		
		public System.Data.Linq.Table<satisfaccion> satisfaccion
		{
			get
			{
				return this.GetTable<satisfaccion>();
			}
		}
		
		public System.Data.Linq.Table<servicio> servicio
		{
			get
			{
				return this.GetTable<servicio>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.usuario")]
	public partial class usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idUser;
		
		private string _email;
		
		private string _password;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidUserChanging(int value);
    partial void OnidUserChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    #endregion
		
		public usuario()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUser", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idUser
		{
			get
			{
				return this._idUser;
			}
			set
			{
				if ((this._idUser != value))
				{
					this.OnidUserChanging(value);
					this.SendPropertyChanging();
					this._idUser = value;
					this.SendPropertyChanged("idUser");
					this.OnidUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.consumo")]
	public partial class consumo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idConsumo;
		
		private int _idHuesped;
		
		private int _idServicio;
		
		private int _cantidad;
		
		private System.DateTime _fecha;
		
		private System.TimeSpan _hora;
		
		private EntitySet<factura> _factura;
		
		private EntityRef<huesped> _huesped;
		
		private EntityRef<servicio> _servicio;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidConsumoChanging(int value);
    partial void OnidConsumoChanged();
    partial void OnidHuespedChanging(int value);
    partial void OnidHuespedChanged();
    partial void OnidServicioChanging(int value);
    partial void OnidServicioChanged();
    partial void OncantidadChanging(int value);
    partial void OncantidadChanged();
    partial void OnfechaChanging(System.DateTime value);
    partial void OnfechaChanged();
    partial void OnhoraChanging(System.TimeSpan value);
    partial void OnhoraChanged();
    #endregion
		
		public consumo()
		{
			this._factura = new EntitySet<factura>(new Action<factura>(this.attach_factura), new Action<factura>(this.detach_factura));
			this._huesped = default(EntityRef<huesped>);
			this._servicio = default(EntityRef<servicio>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idConsumo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idConsumo
		{
			get
			{
				return this._idConsumo;
			}
			set
			{
				if ((this._idConsumo != value))
				{
					this.OnidConsumoChanging(value);
					this.SendPropertyChanging();
					this._idConsumo = value;
					this.SendPropertyChanged("idConsumo");
					this.OnidConsumoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idHuesped", DbType="Int NOT NULL")]
		public int idHuesped
		{
			get
			{
				return this._idHuesped;
			}
			set
			{
				if ((this._idHuesped != value))
				{
					if (this._huesped.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidHuespedChanging(value);
					this.SendPropertyChanging();
					this._idHuesped = value;
					this.SendPropertyChanged("idHuesped");
					this.OnidHuespedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idServicio", DbType="Int NOT NULL")]
		public int idServicio
		{
			get
			{
				return this._idServicio;
			}
			set
			{
				if ((this._idServicio != value))
				{
					if (this._servicio.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidServicioChanging(value);
					this.SendPropertyChanging();
					this._idServicio = value;
					this.SendPropertyChanged("idServicio");
					this.OnidServicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad", DbType="Int NOT NULL")]
		public int cantidad
		{
			get
			{
				return this._cantidad;
			}
			set
			{
				if ((this._cantidad != value))
				{
					this.OncantidadChanging(value);
					this.SendPropertyChanging();
					this._cantidad = value;
					this.SendPropertyChanged("cantidad");
					this.OncantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="Date NOT NULL")]
		public System.DateTime fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this.OnfechaChanging(value);
					this.SendPropertyChanging();
					this._fecha = value;
					this.SendPropertyChanged("fecha");
					this.OnfechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hora", DbType="Time NOT NULL")]
		public System.TimeSpan hora
		{
			get
			{
				return this._hora;
			}
			set
			{
				if ((this._hora != value))
				{
					this.OnhoraChanging(value);
					this.SendPropertyChanging();
					this._hora = value;
					this.SendPropertyChanged("hora");
					this.OnhoraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="consumo_factura", Storage="_factura", ThisKey="idConsumo", OtherKey="idConsumo")]
		public EntitySet<factura> factura
		{
			get
			{
				return this._factura;
			}
			set
			{
				this._factura.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="huesped_consumo", Storage="_huesped", ThisKey="idHuesped", OtherKey="idHuesped", IsForeignKey=true)]
		public huesped huesped
		{
			get
			{
				return this._huesped.Entity;
			}
			set
			{
				huesped previousValue = this._huesped.Entity;
				if (((previousValue != value) 
							|| (this._huesped.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._huesped.Entity = null;
						previousValue.consumo.Remove(this);
					}
					this._huesped.Entity = value;
					if ((value != null))
					{
						value.consumo.Add(this);
						this._idHuesped = value.idHuesped;
					}
					else
					{
						this._idHuesped = default(int);
					}
					this.SendPropertyChanged("huesped");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="servicio_consumo", Storage="_servicio", ThisKey="idServicio", OtherKey="idServicio", IsForeignKey=true)]
		public servicio servicio
		{
			get
			{
				return this._servicio.Entity;
			}
			set
			{
				servicio previousValue = this._servicio.Entity;
				if (((previousValue != value) 
							|| (this._servicio.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._servicio.Entity = null;
						previousValue.consumo.Remove(this);
					}
					this._servicio.Entity = value;
					if ((value != null))
					{
						value.consumo.Add(this);
						this._idServicio = value.idServicio;
					}
					else
					{
						this._idServicio = default(int);
					}
					this.SendPropertyChanged("servicio");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_factura(factura entity)
		{
			this.SendPropertyChanging();
			entity.consumo = this;
		}
		
		private void detach_factura(factura entity)
		{
			this.SendPropertyChanging();
			entity.consumo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.empleado")]
	public partial class empleado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idEmpleado;
		
		private string _nombre;
		
		private string _apellido_pat;
		
		private string _apellido_mat;
		
		private string _sexo;
		
		private string _telefono;
		
		private string _correo;
		
		private string _rfc;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidEmpleadoChanging(int value);
    partial void OnidEmpleadoChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void Onapellido_patChanging(string value);
    partial void Onapellido_patChanged();
    partial void Onapellido_matChanging(string value);
    partial void Onapellido_matChanged();
    partial void OnsexoChanging(string value);
    partial void OnsexoChanged();
    partial void OntelefonoChanging(string value);
    partial void OntelefonoChanged();
    partial void OncorreoChanging(string value);
    partial void OncorreoChanged();
    partial void OnrfcChanging(string value);
    partial void OnrfcChanged();
    #endregion
		
		public empleado()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEmpleado", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idEmpleado
		{
			get
			{
				return this._idEmpleado;
			}
			set
			{
				if ((this._idEmpleado != value))
				{
					this.OnidEmpleadoChanging(value);
					this.SendPropertyChanging();
					this._idEmpleado = value;
					this.SendPropertyChanged("idEmpleado");
					this.OnidEmpleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido_pat", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string apellido_pat
		{
			get
			{
				return this._apellido_pat;
			}
			set
			{
				if ((this._apellido_pat != value))
				{
					this.Onapellido_patChanging(value);
					this.SendPropertyChanging();
					this._apellido_pat = value;
					this.SendPropertyChanged("apellido_pat");
					this.Onapellido_patChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido_mat", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string apellido_mat
		{
			get
			{
				return this._apellido_mat;
			}
			set
			{
				if ((this._apellido_mat != value))
				{
					this.Onapellido_matChanging(value);
					this.SendPropertyChanging();
					this._apellido_mat = value;
					this.SendPropertyChanged("apellido_mat");
					this.Onapellido_matChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sexo", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string sexo
		{
			get
			{
				return this._sexo;
			}
			set
			{
				if ((this._sexo != value))
				{
					this.OnsexoChanging(value);
					this.SendPropertyChanging();
					this._sexo = value;
					this.SendPropertyChanged("sexo");
					this.OnsexoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this.OntelefonoChanging(value);
					this.SendPropertyChanging();
					this._telefono = value;
					this.SendPropertyChanged("telefono");
					this.OntelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string correo
		{
			get
			{
				return this._correo;
			}
			set
			{
				if ((this._correo != value))
				{
					this.OncorreoChanging(value);
					this.SendPropertyChanging();
					this._correo = value;
					this.SendPropertyChanged("correo");
					this.OncorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rfc", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string rfc
		{
			get
			{
				return this._rfc;
			}
			set
			{
				if ((this._rfc != value))
				{
					this.OnrfcChanging(value);
					this.SendPropertyChanging();
					this._rfc = value;
					this.SendPropertyChanged("rfc");
					this.OnrfcChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.factura")]
	public partial class factura : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _numFactura;
		
		private string _nombreEmisor;
		
		private string _telEmisor;
		
		private System.Nullable<System.DateTime> _fecha;
		
		private System.Nullable<System.TimeSpan> _hora;
		
		private int _idHuesped;
		
		private int _idRegistro;
		
		private int _idConsumo;
		
		private int _total;
		
		private EntityRef<consumo> _consumo;
		
		private EntityRef<huesped> _huesped;
		
		private EntityRef<registro> _registro;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnumFacturaChanging(int value);
    partial void OnnumFacturaChanged();
    partial void OnnombreEmisorChanging(string value);
    partial void OnnombreEmisorChanged();
    partial void OntelEmisorChanging(string value);
    partial void OntelEmisorChanged();
    partial void OnfechaChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaChanged();
    partial void OnhoraChanging(System.Nullable<System.TimeSpan> value);
    partial void OnhoraChanged();
    partial void OnidHuespedChanging(int value);
    partial void OnidHuespedChanged();
    partial void OnidRegistroChanging(int value);
    partial void OnidRegistroChanged();
    partial void OnidConsumoChanging(int value);
    partial void OnidConsumoChanged();
    partial void OntotalChanging(int value);
    partial void OntotalChanged();
    #endregion
		
		public factura()
		{
			this._consumo = default(EntityRef<consumo>);
			this._huesped = default(EntityRef<huesped>);
			this._registro = default(EntityRef<registro>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numFactura", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int numFactura
		{
			get
			{
				return this._numFactura;
			}
			set
			{
				if ((this._numFactura != value))
				{
					this.OnnumFacturaChanging(value);
					this.SendPropertyChanging();
					this._numFactura = value;
					this.SendPropertyChanged("numFactura");
					this.OnnumFacturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreEmisor", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombreEmisor
		{
			get
			{
				return this._nombreEmisor;
			}
			set
			{
				if ((this._nombreEmisor != value))
				{
					this.OnnombreEmisorChanging(value);
					this.SendPropertyChanging();
					this._nombreEmisor = value;
					this.SendPropertyChanged("nombreEmisor");
					this.OnnombreEmisorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telEmisor", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string telEmisor
		{
			get
			{
				return this._telEmisor;
			}
			set
			{
				if ((this._telEmisor != value))
				{
					this.OntelEmisorChanging(value);
					this.SendPropertyChanging();
					this._telEmisor = value;
					this.SendPropertyChanged("telEmisor");
					this.OntelEmisorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="Date")]
		public System.Nullable<System.DateTime> fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this.OnfechaChanging(value);
					this.SendPropertyChanging();
					this._fecha = value;
					this.SendPropertyChanged("fecha");
					this.OnfechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hora", DbType="Time")]
		public System.Nullable<System.TimeSpan> hora
		{
			get
			{
				return this._hora;
			}
			set
			{
				if ((this._hora != value))
				{
					this.OnhoraChanging(value);
					this.SendPropertyChanging();
					this._hora = value;
					this.SendPropertyChanged("hora");
					this.OnhoraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idHuesped", DbType="Int NOT NULL")]
		public int idHuesped
		{
			get
			{
				return this._idHuesped;
			}
			set
			{
				if ((this._idHuesped != value))
				{
					if (this._huesped.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidHuespedChanging(value);
					this.SendPropertyChanging();
					this._idHuesped = value;
					this.SendPropertyChanged("idHuesped");
					this.OnidHuespedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idRegistro", DbType="Int NOT NULL")]
		public int idRegistro
		{
			get
			{
				return this._idRegistro;
			}
			set
			{
				if ((this._idRegistro != value))
				{
					if (this._registro.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidRegistroChanging(value);
					this.SendPropertyChanging();
					this._idRegistro = value;
					this.SendPropertyChanged("idRegistro");
					this.OnidRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idConsumo", DbType="Int NOT NULL")]
		public int idConsumo
		{
			get
			{
				return this._idConsumo;
			}
			set
			{
				if ((this._idConsumo != value))
				{
					if (this._consumo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidConsumoChanging(value);
					this.SendPropertyChanging();
					this._idConsumo = value;
					this.SendPropertyChanged("idConsumo");
					this.OnidConsumoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total", DbType="Int NOT NULL")]
		public int total
		{
			get
			{
				return this._total;
			}
			set
			{
				if ((this._total != value))
				{
					this.OntotalChanging(value);
					this.SendPropertyChanging();
					this._total = value;
					this.SendPropertyChanged("total");
					this.OntotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="consumo_factura", Storage="_consumo", ThisKey="idConsumo", OtherKey="idConsumo", IsForeignKey=true)]
		public consumo consumo
		{
			get
			{
				return this._consumo.Entity;
			}
			set
			{
				consumo previousValue = this._consumo.Entity;
				if (((previousValue != value) 
							|| (this._consumo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._consumo.Entity = null;
						previousValue.factura.Remove(this);
					}
					this._consumo.Entity = value;
					if ((value != null))
					{
						value.factura.Add(this);
						this._idConsumo = value.idConsumo;
					}
					else
					{
						this._idConsumo = default(int);
					}
					this.SendPropertyChanged("consumo");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="huesped_factura", Storage="_huesped", ThisKey="idHuesped", OtherKey="idHuesped", IsForeignKey=true)]
		public huesped huesped
		{
			get
			{
				return this._huesped.Entity;
			}
			set
			{
				huesped previousValue = this._huesped.Entity;
				if (((previousValue != value) 
							|| (this._huesped.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._huesped.Entity = null;
						previousValue.factura.Remove(this);
					}
					this._huesped.Entity = value;
					if ((value != null))
					{
						value.factura.Add(this);
						this._idHuesped = value.idHuesped;
					}
					else
					{
						this._idHuesped = default(int);
					}
					this.SendPropertyChanged("huesped");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="registro_factura", Storage="_registro", ThisKey="idRegistro", OtherKey="idRegistro", IsForeignKey=true)]
		public registro registro
		{
			get
			{
				return this._registro.Entity;
			}
			set
			{
				registro previousValue = this._registro.Entity;
				if (((previousValue != value) 
							|| (this._registro.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._registro.Entity = null;
						previousValue.factura.Remove(this);
					}
					this._registro.Entity = value;
					if ((value != null))
					{
						value.factura.Add(this);
						this._idRegistro = value.idRegistro;
					}
					else
					{
						this._idRegistro = default(int);
					}
					this.SendPropertyChanged("registro");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.habitacion")]
	public partial class habitacion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _idHabitacion;
		
		private string _tipo;
		
		private string _capacidad;
		
		private string _disponibilidad;
		
		private int _precio;
		
		private EntitySet<registro> _registro;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidHabitacionChanging(string value);
    partial void OnidHabitacionChanged();
    partial void OntipoChanging(string value);
    partial void OntipoChanged();
    partial void OncapacidadChanging(string value);
    partial void OncapacidadChanged();
    partial void OndisponibilidadChanging(string value);
    partial void OndisponibilidadChanged();
    partial void OnprecioChanging(int value);
    partial void OnprecioChanged();
    #endregion
		
		public habitacion()
		{
			this._registro = new EntitySet<registro>(new Action<registro>(this.attach_registro), new Action<registro>(this.detach_registro));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idHabitacion", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idHabitacion
		{
			get
			{
				return this._idHabitacion;
			}
			set
			{
				if ((this._idHabitacion != value))
				{
					this.OnidHabitacionChanging(value);
					this.SendPropertyChanging();
					this._idHabitacion = value;
					this.SendPropertyChanged("idHabitacion");
					this.OnidHabitacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string tipo
		{
			get
			{
				return this._tipo;
			}
			set
			{
				if ((this._tipo != value))
				{
					this.OntipoChanging(value);
					this.SendPropertyChanging();
					this._tipo = value;
					this.SendPropertyChanged("tipo");
					this.OntipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_capacidad", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string capacidad
		{
			get
			{
				return this._capacidad;
			}
			set
			{
				if ((this._capacidad != value))
				{
					this.OncapacidadChanging(value);
					this.SendPropertyChanging();
					this._capacidad = value;
					this.SendPropertyChanged("capacidad");
					this.OncapacidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_disponibilidad", DbType="VarChar(15)")]
		public string disponibilidad
		{
			get
			{
				return this._disponibilidad;
			}
			set
			{
				if ((this._disponibilidad != value))
				{
					this.OndisponibilidadChanging(value);
					this.SendPropertyChanging();
					this._disponibilidad = value;
					this.SendPropertyChanged("disponibilidad");
					this.OndisponibilidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio", DbType="Int NOT NULL")]
		public int precio
		{
			get
			{
				return this._precio;
			}
			set
			{
				if ((this._precio != value))
				{
					this.OnprecioChanging(value);
					this.SendPropertyChanging();
					this._precio = value;
					this.SendPropertyChanged("precio");
					this.OnprecioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="habitacion_registro", Storage="_registro", ThisKey="idHabitacion", OtherKey="idHabitacion")]
		public EntitySet<registro> registro
		{
			get
			{
				return this._registro;
			}
			set
			{
				this._registro.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_registro(registro entity)
		{
			this.SendPropertyChanging();
			entity.habitacion = this;
		}
		
		private void detach_registro(registro entity)
		{
			this.SendPropertyChanging();
			entity.habitacion = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.huesped")]
	public partial class huesped : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idHuesped;
		
		private string _nombres;
		
		private string _apellido_pat;
		
		private string _apellido_mat;
		
		private int _edad;
		
		private string _sexo;
		
		private System.DateTime _fecha_nac;
		
		private string _lugar_nac;
		
		private string _direccion;
		
		private string _tel_casa;
		
		private string _tel_celular;
		
		private string _correo;
		
		private string _rfc;
		
		private System.Nullable<int> _numVisita;
		
		private EntitySet<consumo> _consumo;
		
		private EntitySet<factura> _factura;
		
		private EntitySet<registro> _registro;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidHuespedChanging(int value);
    partial void OnidHuespedChanged();
    partial void OnnombresChanging(string value);
    partial void OnnombresChanged();
    partial void Onapellido_patChanging(string value);
    partial void Onapellido_patChanged();
    partial void Onapellido_matChanging(string value);
    partial void Onapellido_matChanged();
    partial void OnedadChanging(int value);
    partial void OnedadChanged();
    partial void OnsexoChanging(string value);
    partial void OnsexoChanged();
    partial void Onfecha_nacChanging(System.DateTime value);
    partial void Onfecha_nacChanged();
    partial void Onlugar_nacChanging(string value);
    partial void Onlugar_nacChanged();
    partial void OndireccionChanging(string value);
    partial void OndireccionChanged();
    partial void Ontel_casaChanging(string value);
    partial void Ontel_casaChanged();
    partial void Ontel_celularChanging(string value);
    partial void Ontel_celularChanged();
    partial void OncorreoChanging(string value);
    partial void OncorreoChanged();
    partial void OnrfcChanging(string value);
    partial void OnrfcChanged();
    partial void OnnumVisitaChanging(System.Nullable<int> value);
    partial void OnnumVisitaChanged();
    #endregion
		
		public huesped()
		{
			this._consumo = new EntitySet<consumo>(new Action<consumo>(this.attach_consumo), new Action<consumo>(this.detach_consumo));
			this._factura = new EntitySet<factura>(new Action<factura>(this.attach_factura), new Action<factura>(this.detach_factura));
			this._registro = new EntitySet<registro>(new Action<registro>(this.attach_registro), new Action<registro>(this.detach_registro));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idHuesped", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idHuesped
		{
			get
			{
				return this._idHuesped;
			}
			set
			{
				if ((this._idHuesped != value))
				{
					this.OnidHuespedChanging(value);
					this.SendPropertyChanging();
					this._idHuesped = value;
					this.SendPropertyChanged("idHuesped");
					this.OnidHuespedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombres", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string nombres
		{
			get
			{
				return this._nombres;
			}
			set
			{
				if ((this._nombres != value))
				{
					this.OnnombresChanging(value);
					this.SendPropertyChanging();
					this._nombres = value;
					this.SendPropertyChanged("nombres");
					this.OnnombresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido_pat", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string apellido_pat
		{
			get
			{
				return this._apellido_pat;
			}
			set
			{
				if ((this._apellido_pat != value))
				{
					this.Onapellido_patChanging(value);
					this.SendPropertyChanging();
					this._apellido_pat = value;
					this.SendPropertyChanged("apellido_pat");
					this.Onapellido_patChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido_mat", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string apellido_mat
		{
			get
			{
				return this._apellido_mat;
			}
			set
			{
				if ((this._apellido_mat != value))
				{
					this.Onapellido_matChanging(value);
					this.SendPropertyChanging();
					this._apellido_mat = value;
					this.SendPropertyChanged("apellido_mat");
					this.Onapellido_matChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_edad", DbType="Int NOT NULL")]
		public int edad
		{
			get
			{
				return this._edad;
			}
			set
			{
				if ((this._edad != value))
				{
					this.OnedadChanging(value);
					this.SendPropertyChanging();
					this._edad = value;
					this.SendPropertyChanged("edad");
					this.OnedadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sexo", DbType="VarChar(15)")]
		public string sexo
		{
			get
			{
				return this._sexo;
			}
			set
			{
				if ((this._sexo != value))
				{
					this.OnsexoChanging(value);
					this.SendPropertyChanging();
					this._sexo = value;
					this.SendPropertyChanged("sexo");
					this.OnsexoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_nac", DbType="Date NOT NULL")]
		public System.DateTime fecha_nac
		{
			get
			{
				return this._fecha_nac;
			}
			set
			{
				if ((this._fecha_nac != value))
				{
					this.Onfecha_nacChanging(value);
					this.SendPropertyChanging();
					this._fecha_nac = value;
					this.SendPropertyChanged("fecha_nac");
					this.Onfecha_nacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lugar_nac", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string lugar_nac
		{
			get
			{
				return this._lugar_nac;
			}
			set
			{
				if ((this._lugar_nac != value))
				{
					this.Onlugar_nacChanging(value);
					this.SendPropertyChanging();
					this._lugar_nac = value;
					this.SendPropertyChanged("lugar_nac");
					this.Onlugar_nacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this.OndireccionChanging(value);
					this.SendPropertyChanging();
					this._direccion = value;
					this.SendPropertyChanged("direccion");
					this.OndireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tel_casa", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string tel_casa
		{
			get
			{
				return this._tel_casa;
			}
			set
			{
				if ((this._tel_casa != value))
				{
					this.Ontel_casaChanging(value);
					this.SendPropertyChanging();
					this._tel_casa = value;
					this.SendPropertyChanged("tel_casa");
					this.Ontel_casaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tel_celular", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string tel_celular
		{
			get
			{
				return this._tel_celular;
			}
			set
			{
				if ((this._tel_celular != value))
				{
					this.Ontel_celularChanging(value);
					this.SendPropertyChanging();
					this._tel_celular = value;
					this.SendPropertyChanged("tel_celular");
					this.Ontel_celularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string correo
		{
			get
			{
				return this._correo;
			}
			set
			{
				if ((this._correo != value))
				{
					this.OncorreoChanging(value);
					this.SendPropertyChanging();
					this._correo = value;
					this.SendPropertyChanged("correo");
					this.OncorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rfc", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string rfc
		{
			get
			{
				return this._rfc;
			}
			set
			{
				if ((this._rfc != value))
				{
					this.OnrfcChanging(value);
					this.SendPropertyChanging();
					this._rfc = value;
					this.SendPropertyChanged("rfc");
					this.OnrfcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numVisita", DbType="Int")]
		public System.Nullable<int> numVisita
		{
			get
			{
				return this._numVisita;
			}
			set
			{
				if ((this._numVisita != value))
				{
					this.OnnumVisitaChanging(value);
					this.SendPropertyChanging();
					this._numVisita = value;
					this.SendPropertyChanged("numVisita");
					this.OnnumVisitaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="huesped_consumo", Storage="_consumo", ThisKey="idHuesped", OtherKey="idHuesped")]
		public EntitySet<consumo> consumo
		{
			get
			{
				return this._consumo;
			}
			set
			{
				this._consumo.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="huesped_factura", Storage="_factura", ThisKey="idHuesped", OtherKey="idHuesped")]
		public EntitySet<factura> factura
		{
			get
			{
				return this._factura;
			}
			set
			{
				this._factura.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="huesped_registro", Storage="_registro", ThisKey="idHuesped", OtherKey="idHuesped")]
		public EntitySet<registro> registro
		{
			get
			{
				return this._registro;
			}
			set
			{
				this._registro.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_consumo(consumo entity)
		{
			this.SendPropertyChanging();
			entity.huesped = this;
		}
		
		private void detach_consumo(consumo entity)
		{
			this.SendPropertyChanging();
			entity.huesped = null;
		}
		
		private void attach_factura(factura entity)
		{
			this.SendPropertyChanging();
			entity.huesped = this;
		}
		
		private void detach_factura(factura entity)
		{
			this.SendPropertyChanging();
			entity.huesped = null;
		}
		
		private void attach_registro(registro entity)
		{
			this.SendPropertyChanging();
			entity.huesped = this;
		}
		
		private void detach_registro(registro entity)
		{
			this.SendPropertyChanging();
			entity.huesped = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.queja")]
	public partial class queja : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idQueja;
		
		private string _descripcion;
		
		private System.Nullable<System.DateTime> _fecha;
		
		private System.Nullable<System.TimeSpan> _hora;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidQuejaChanging(int value);
    partial void OnidQuejaChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void OnfechaChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaChanged();
    partial void OnhoraChanging(System.Nullable<System.TimeSpan> value);
    partial void OnhoraChanged();
    #endregion
		
		public queja()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idQueja", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idQueja
		{
			get
			{
				return this._idQueja;
			}
			set
			{
				if ((this._idQueja != value))
				{
					this.OnidQuejaChanging(value);
					this.SendPropertyChanging();
					this._idQueja = value;
					this.SendPropertyChanged("idQueja");
					this.OnidQuejaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="NVarChar(100)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="Date")]
		public System.Nullable<System.DateTime> fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this.OnfechaChanging(value);
					this.SendPropertyChanging();
					this._fecha = value;
					this.SendPropertyChanged("fecha");
					this.OnfechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hora", DbType="Time")]
		public System.Nullable<System.TimeSpan> hora
		{
			get
			{
				return this._hora;
			}
			set
			{
				if ((this._hora != value))
				{
					this.OnhoraChanging(value);
					this.SendPropertyChanging();
					this._hora = value;
					this.SendPropertyChanged("hora");
					this.OnhoraChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.registro")]
	public partial class registro : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idRegistro;
		
		private int _idHuesped;
		
		private string _idHabitacion;
		
		private System.DateTime _fecha;
		
		private System.TimeSpan _hora;
		
		private int _dias;
		
		private System.Nullable<int> _descuento;
		
		private EntitySet<factura> _factura;
		
		private EntityRef<habitacion> _habitacion;
		
		private EntityRef<huesped> _huesped;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidRegistroChanging(int value);
    partial void OnidRegistroChanged();
    partial void OnidHuespedChanging(int value);
    partial void OnidHuespedChanged();
    partial void OnidHabitacionChanging(string value);
    partial void OnidHabitacionChanged();
    partial void OnfechaChanging(System.DateTime value);
    partial void OnfechaChanged();
    partial void OnhoraChanging(System.TimeSpan value);
    partial void OnhoraChanged();
    partial void OndiasChanging(int value);
    partial void OndiasChanged();
    partial void OndescuentoChanging(System.Nullable<int> value);
    partial void OndescuentoChanged();
    #endregion
		
		public registro()
		{
			this._factura = new EntitySet<factura>(new Action<factura>(this.attach_factura), new Action<factura>(this.detach_factura));
			this._habitacion = default(EntityRef<habitacion>);
			this._huesped = default(EntityRef<huesped>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idRegistro", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idRegistro
		{
			get
			{
				return this._idRegistro;
			}
			set
			{
				if ((this._idRegistro != value))
				{
					this.OnidRegistroChanging(value);
					this.SendPropertyChanging();
					this._idRegistro = value;
					this.SendPropertyChanged("idRegistro");
					this.OnidRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idHuesped", DbType="Int NOT NULL")]
		public int idHuesped
		{
			get
			{
				return this._idHuesped;
			}
			set
			{
				if ((this._idHuesped != value))
				{
					if (this._huesped.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidHuespedChanging(value);
					this.SendPropertyChanging();
					this._idHuesped = value;
					this.SendPropertyChanged("idHuesped");
					this.OnidHuespedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idHabitacion", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string idHabitacion
		{
			get
			{
				return this._idHabitacion;
			}
			set
			{
				if ((this._idHabitacion != value))
				{
					if (this._habitacion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidHabitacionChanging(value);
					this.SendPropertyChanging();
					this._idHabitacion = value;
					this.SendPropertyChanged("idHabitacion");
					this.OnidHabitacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="Date NOT NULL")]
		public System.DateTime fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this.OnfechaChanging(value);
					this.SendPropertyChanging();
					this._fecha = value;
					this.SendPropertyChanged("fecha");
					this.OnfechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hora", DbType="Time NOT NULL")]
		public System.TimeSpan hora
		{
			get
			{
				return this._hora;
			}
			set
			{
				if ((this._hora != value))
				{
					this.OnhoraChanging(value);
					this.SendPropertyChanging();
					this._hora = value;
					this.SendPropertyChanged("hora");
					this.OnhoraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dias", DbType="Int NOT NULL")]
		public int dias
		{
			get
			{
				return this._dias;
			}
			set
			{
				if ((this._dias != value))
				{
					this.OndiasChanging(value);
					this.SendPropertyChanging();
					this._dias = value;
					this.SendPropertyChanged("dias");
					this.OndiasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descuento", DbType="Int")]
		public System.Nullable<int> descuento
		{
			get
			{
				return this._descuento;
			}
			set
			{
				if ((this._descuento != value))
				{
					this.OndescuentoChanging(value);
					this.SendPropertyChanging();
					this._descuento = value;
					this.SendPropertyChanged("descuento");
					this.OndescuentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="registro_factura", Storage="_factura", ThisKey="idRegistro", OtherKey="idRegistro")]
		public EntitySet<factura> factura
		{
			get
			{
				return this._factura;
			}
			set
			{
				this._factura.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="habitacion_registro", Storage="_habitacion", ThisKey="idHabitacion", OtherKey="idHabitacion", IsForeignKey=true)]
		public habitacion habitacion
		{
			get
			{
				return this._habitacion.Entity;
			}
			set
			{
				habitacion previousValue = this._habitacion.Entity;
				if (((previousValue != value) 
							|| (this._habitacion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._habitacion.Entity = null;
						previousValue.registro.Remove(this);
					}
					this._habitacion.Entity = value;
					if ((value != null))
					{
						value.registro.Add(this);
						this._idHabitacion = value.idHabitacion;
					}
					else
					{
						this._idHabitacion = default(string);
					}
					this.SendPropertyChanged("habitacion");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="huesped_registro", Storage="_huesped", ThisKey="idHuesped", OtherKey="idHuesped", IsForeignKey=true)]
		public huesped huesped
		{
			get
			{
				return this._huesped.Entity;
			}
			set
			{
				huesped previousValue = this._huesped.Entity;
				if (((previousValue != value) 
							|| (this._huesped.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._huesped.Entity = null;
						previousValue.registro.Remove(this);
					}
					this._huesped.Entity = value;
					if ((value != null))
					{
						value.registro.Add(this);
						this._idHuesped = value.idHuesped;
					}
					else
					{
						this._idHuesped = default(int);
					}
					this.SendPropertyChanged("huesped");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_factura(factura entity)
		{
			this.SendPropertyChanging();
			entity.registro = this;
		}
		
		private void detach_factura(factura entity)
		{
			this.SendPropertyChanging();
			entity.registro = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.satisfaccion")]
	public partial class satisfaccion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idSatisfaccion;
		
		private string _descripcion;
		
		private System.Nullable<int> _calificacion;
		
		private System.Nullable<System.DateTime> _fecha;
		
		private System.Nullable<System.TimeSpan> _hora;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidSatisfaccionChanging(int value);
    partial void OnidSatisfaccionChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void OncalificacionChanging(System.Nullable<int> value);
    partial void OncalificacionChanged();
    partial void OnfechaChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaChanged();
    partial void OnhoraChanging(System.Nullable<System.TimeSpan> value);
    partial void OnhoraChanged();
    #endregion
		
		public satisfaccion()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idSatisfaccion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idSatisfaccion
		{
			get
			{
				return this._idSatisfaccion;
			}
			set
			{
				if ((this._idSatisfaccion != value))
				{
					this.OnidSatisfaccionChanging(value);
					this.SendPropertyChanging();
					this._idSatisfaccion = value;
					this.SendPropertyChanged("idSatisfaccion");
					this.OnidSatisfaccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="NVarChar(100)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_calificacion", DbType="Int")]
		public System.Nullable<int> calificacion
		{
			get
			{
				return this._calificacion;
			}
			set
			{
				if ((this._calificacion != value))
				{
					this.OncalificacionChanging(value);
					this.SendPropertyChanging();
					this._calificacion = value;
					this.SendPropertyChanged("calificacion");
					this.OncalificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="Date")]
		public System.Nullable<System.DateTime> fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this.OnfechaChanging(value);
					this.SendPropertyChanging();
					this._fecha = value;
					this.SendPropertyChanged("fecha");
					this.OnfechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hora", DbType="Time")]
		public System.Nullable<System.TimeSpan> hora
		{
			get
			{
				return this._hora;
			}
			set
			{
				if ((this._hora != value))
				{
					this.OnhoraChanging(value);
					this.SendPropertyChanging();
					this._hora = value;
					this.SendPropertyChanged("hora");
					this.OnhoraChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.servicio")]
	public partial class servicio : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idServicio;
		
		private string _tipo;
		
		private string _descripcion;
		
		private System.Nullable<System.DateTime> _fecha;
		
		private System.Nullable<System.TimeSpan> _hora;
		
		private int _costo;
		
		private EntitySet<consumo> _consumo;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidServicioChanging(int value);
    partial void OnidServicioChanged();
    partial void OntipoChanging(string value);
    partial void OntipoChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void OnfechaChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaChanged();
    partial void OnhoraChanging(System.Nullable<System.TimeSpan> value);
    partial void OnhoraChanged();
    partial void OncostoChanging(int value);
    partial void OncostoChanged();
    #endregion
		
		public servicio()
		{
			this._consumo = new EntitySet<consumo>(new Action<consumo>(this.attach_consumo), new Action<consumo>(this.detach_consumo));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idServicio", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idServicio
		{
			get
			{
				return this._idServicio;
			}
			set
			{
				if ((this._idServicio != value))
				{
					this.OnidServicioChanging(value);
					this.SendPropertyChanging();
					this._idServicio = value;
					this.SendPropertyChanged("idServicio");
					this.OnidServicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string tipo
		{
			get
			{
				return this._tipo;
			}
			set
			{
				if ((this._tipo != value))
				{
					this.OntipoChanging(value);
					this.SendPropertyChanging();
					this._tipo = value;
					this.SendPropertyChanged("tipo");
					this.OntipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="Date")]
		public System.Nullable<System.DateTime> fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this.OnfechaChanging(value);
					this.SendPropertyChanging();
					this._fecha = value;
					this.SendPropertyChanged("fecha");
					this.OnfechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hora", DbType="Time")]
		public System.Nullable<System.TimeSpan> hora
		{
			get
			{
				return this._hora;
			}
			set
			{
				if ((this._hora != value))
				{
					this.OnhoraChanging(value);
					this.SendPropertyChanging();
					this._hora = value;
					this.SendPropertyChanged("hora");
					this.OnhoraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_costo", DbType="Int NOT NULL")]
		public int costo
		{
			get
			{
				return this._costo;
			}
			set
			{
				if ((this._costo != value))
				{
					this.OncostoChanging(value);
					this.SendPropertyChanging();
					this._costo = value;
					this.SendPropertyChanged("costo");
					this.OncostoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="servicio_consumo", Storage="_consumo", ThisKey="idServicio", OtherKey="idServicio")]
		public EntitySet<consumo> consumo
		{
			get
			{
				return this._consumo;
			}
			set
			{
				this._consumo.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_consumo(consumo entity)
		{
			this.SendPropertyChanging();
			entity.servicio = this;
		}
		
		private void detach_consumo(consumo entity)
		{
			this.SendPropertyChanging();
			entity.servicio = null;
		}
	}
}
#pragma warning restore 1591
