<?xml version="1.0" encoding="utf-8"?><Database Name="hotel5" Class="EntidadesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost\SQLEXPRESS;Initial Catalog=hotel5;Integrated Security=True" SettingsObjectName="Modelo.Properties.Settings" SettingsPropertyName="hotel5ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.usuario" Member="usuario">
    <Type Name="usuario">
      <Column Name="idUser" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.consumo" Member="consumo">
    <Type Name="consumo">
      <Column Name="idConsumo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idHuesped" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idServicio" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="cantidad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fecha" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="hora" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Association Name="consumo_factura" Member="factura" ThisKey="idConsumo" OtherKey="idConsumo" Type="factura" />
      <Association Name="huesped_consumo" Member="huesped" ThisKey="idHuesped" OtherKey="idHuesped" Type="huesped" IsForeignKey="true" />
      <Association Name="servicio_consumo" Member="servicio" ThisKey="idServicio" OtherKey="idServicio" Type="servicio" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.empleado" Member="empleado">
    <Type Name="empleado">
      <Column Name="idEmpleado" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="apellido_pat" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="apellido_mat" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="sexo" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="telefono" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="correo" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="rfc" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.factura" Member="factura">
    <Type Name="factura">
      <Column Name="numFactura" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombreEmisor" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="telEmisor" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="fecha" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="hora" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="idHuesped" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idRegistro" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idConsumo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="total" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="consumo_factura" Member="consumo" ThisKey="idConsumo" OtherKey="idConsumo" Type="consumo" IsForeignKey="true" />
      <Association Name="huesped_factura" Member="huesped" ThisKey="idHuesped" OtherKey="idHuesped" Type="huesped" IsForeignKey="true" />
      <Association Name="registro_factura" Member="registro" ThisKey="idRegistro" OtherKey="idRegistro" Type="registro" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.habitacion" Member="habitacion">
    <Type Name="habitacion">
      <Column Name="idHabitacion" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tipo" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="capacidad" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="disponibilidad" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="precio" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="habitacion_registro" Member="registro" ThisKey="idHabitacion" OtherKey="idHabitacion" Type="registro" />
    </Type>
  </Table>
  <Table Name="dbo.huesped" Member="huesped">
    <Type Name="huesped">
      <Column Name="idHuesped" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombres" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="apellido_pat" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="apellido_mat" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="edad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="sexo" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="fecha_nac" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="lugar_nac" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="direccion" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="tel_casa" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="tel_celular" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="correo" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="rfc" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="numVisita" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="huesped_consumo" Member="consumo" ThisKey="idHuesped" OtherKey="idHuesped" Type="consumo" />
      <Association Name="huesped_factura" Member="factura" ThisKey="idHuesped" OtherKey="idHuesped" Type="factura" />
      <Association Name="huesped_registro" Member="registro" ThisKey="idHuesped" OtherKey="idHuesped" Type="registro" />
    </Type>
  </Table>
  <Table Name="dbo.queja" Member="queja">
    <Type Name="queja">
      <Column Name="idQueja" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="fecha" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="hora" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.registro" Member="registro">
    <Type Name="registro">
      <Column Name="idRegistro" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idHuesped" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idHabitacion" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="fecha" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="hora" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="dias" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="descuento" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="registro_factura" Member="factura" ThisKey="idRegistro" OtherKey="idRegistro" Type="factura" />
      <Association Name="habitacion_registro" Member="habitacion" ThisKey="idHabitacion" OtherKey="idHabitacion" Type="habitacion" IsForeignKey="true" />
      <Association Name="huesped_registro" Member="huesped" ThisKey="idHuesped" OtherKey="idHuesped" Type="huesped" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.satisfaccion" Member="satisfaccion">
    <Type Name="satisfaccion">
      <Column Name="idSatisfaccion" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="calificacion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fecha" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="hora" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.servicio" Member="servicio">
    <Type Name="servicio">
      <Column Name="idServicio" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tipo" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="fecha" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="hora" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="costo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="servicio_consumo" Member="consumo" ThisKey="idServicio" OtherKey="idServicio" Type="consumo" />
    </Type>
  </Table>
</Database>